pub const SERVER_ADDR_ENV_VAR_NAME: &str = "SERVER_ADDR";
pub const KEYPAIRS_STORE_PATH_ENV_VAR_NAME: &str = "KEYPAIRS_STORE_PATH";
pub const POSTGRESQL_URL_ENV_VAR_NAME: &str = "POSTGRESQL_URL";

pub const SESSION_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "SESSION_EXPIRATION_SECONDS";
pub const SESSION_EXPIRATION_SECONDS_DEFAULT: usize = 7 * 24 * 60 * 60;

pub const ACCESS_TOKEN_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "ACCESS_TOKEN_EXPIRATION_SECONDS";
pub const ACCESS_TOKEN_EXPIRATION_SECONDS_DEFAULT: usize = 15 * 60;
pub const ACCESS_TOKEN_AUDIENCE: &str = "nimbus";
pub const ACCESS_TOKEN_ISSUER: &str = "nimbus-auth";

pub const POSTGRESDB_MAX_CONNECTIONS_ENV_VAR_NAME: &str = "POSTGRESDB_MAX_CONNECTIONS";
pub const POSTGRESDB_MAX_CONNECTIONS_DEFAULT: usize = 24;

pub const USE_HSTS_ENV_VAR_NAME: &str = "USE_HSTS";
pub const USE_HSTS_DEFAULT: bool = false;

pub const CORS_ORIGINS_COMMA_SEPARATED_ENV_VAR_NAME: &str = "CORS_ORIGINS_COMMA_SEPARATED";
pub const CORS_ORIGINS_COMMA_SEPARATED_DEFAULT: &str = "";

pub const CHANNEL_BUFFER_SIZE_DEFAULT: usize = 4096;

pub const PASSWORD_MIN_LENGTH_INCLUSIVE: usize = 8;
pub const PASSWORD_MAX_LENGTH_INCLUSIVE: usize = 32;

pub const USERNAME_MIN_LENGTH_INCLUSIVE: usize = 4;
pub const USERNAME_MAX_LENGTH_INCLUSIVE: usize = 32;

pub const CLIENT_TYPE_HEADER_NAME: &str = "x-client-type";
pub const CLIENT_TYPE_BROWSER_HEADER_VALUE: &str = "browser";
pub const CLIENT_TYPE_MOBILE_HEADER_VALUE: &str = "mobile";
pub const CLIENT_TYPE_PC_HEADER_VALUE: &str = "pc";

pub const SESSION_COOKIE_NAME: &str = "session_id";
pub const SESSION_COOKIE_EXP_TIMESTAMP_NAME: &str = "session_exp_timestamp";

pub const SESSION_HEADER_NAME: &str = "x-session-id";
pub const SESSION_HEADER_EXP_TIMESTAMP_NAME: &str = "x-session-exp-timestamp";
