pub const SERVER_ADDR_ENV_VAR_NAME: &str = "SERVER_ADDR";
pub const KEYPAIRS_STORE_PATH_ENV_VAR_NAME: &str = "KEYPAIRS_STORE_PATH";
pub const POSTGRESQL_URL_ENV_VAR_NAME: &str = "POSTGRESQL_URL";

pub const SESSION_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "SESSION_EXPIRATION_SECONDS";
pub const SESSION_EXPIRATION_SECONDS_DEFAULT: u32 = 7 * 24 * 60 * 60;

pub const ACCESS_TOKEN_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "ACCESS_TOKEN_EXPIRATION_SECONDS";
pub const ACCESS_TOKEN_EXPIRATION_SECONDS_DEFAULT: u32 = 15 * 60;
pub const ACCESS_TOKEN_AUDIENCE: &str = "nimbus";
pub const ACCESS_TOKEN_ISSUER: &str = "nimbus-auth";

pub const POSTGRESDB_MAX_CONNECTIONS_ENV_VAR_NAME: &str = "POSTGRESDB_MAX_CONNECTIONS";
pub const POSTGRESDB_MAX_CONNECTIONS_DEFAULT: u32 = 24;

pub const CHANNEL_BUFFER_SIZE_DEFAULT: usize = 4096;
