pub const SESSION_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "SESSION_EXPIRATION_SECONDS";
pub const SESSION_EXPIRATION_SECONDS_DEFAULT: u32 = 7 * 24 * 60 * 60;

pub const ACCESS_TOKEN_EXPIRATION_SECONDS_ENV_VAR_NAME: &str = "ACCESS_TOKEN_EXPIRATION_SECONDS";
pub const ACCESS_TOKEN_EXPIRATION_SECONDS_DEFAULT: u32 = 15 * 60;
pub const ACCESS_TOKEN_AUDIENCE: &str = "nimbus";
pub const ACCESS_TOKEN_ISSUER: &str = "nimbus-auth";
