[package]
name = "nimbus_auth_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace dependencies
tracing.workspace = true
tracing-subscriber.workspace = true
time.workspace = true
ulid.workspace = true
thiserror.workspace = true