[package]
name = "nimbus_auth_infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local crates dependencies
nimbus_auth_domain = { path = "../domain" }
nimbus_auth_shared = { path = "../shared" }

# Workspace dependencies
tracing.workspace = true
tracing-subscriber.workspace = true
time.workspace = true
ulid.workspace = true
thiserror.workspace = true

# Runtime
tokio = { version = "1.45.1", features = ["full"] }

# Api
axum = "0.8.4"

# Protobuf
prost = "0.12"

[build-dependencies]
prost-build = "0.12"