[workspace]
members = [
    "domain",
    "application",
    "infrastructure",
    "entrypoint",
    "shared"
]

[workspace.dependencies]
# Tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# Common
time = "0.3.42"
ulid = "1.2.1"
thiserror = "2.0.16"